spring:
  data:
    mongodb:
      database: airquality-db
      uri: ${MONGODB_URL:mongodb+srv://jagudo2514:S0GMi5G9D6z4hiTI@cluster0.xor7f74.mongodb.net}
  application:
    name: ms-collection

server:
  port: 8089

## Configuracion del cliente de Eureka
eureka:
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:ms-collection}
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:8761/eureka}

saviasoft:
  app:
    entity:
      device:
        findByUid:
          url: ${ENTITY_URL_FIND_BY_UID:http://127.0.0.1:8088/devices/byUid/%s}
      system-config:
        get:
          url: ${ENTITY_URL_GET:http://127.0.0.1:8088/system-config/1}